export const COUNTRY_DIAL_CODES: { [key: string]: string } = {
  'US': '+1',
  'GB': '+44',
  'IN': '+91',
  'CA': '+1',
  'AU': '+61',
  'DE': '+49',
  'FR': '+33',
  'IT': '+39',
  'ES': '+34',
  'BR': '+55',
  'JP': '+81',
  'KR': '+82',
  'CN': '+86',
  'RU': '+7',
};